//@version=4
study('chartex2', overlay=true)
if barstate.islast
    label.new(x=1619168400000, y=2000, xloc = xloc.bar_time)
e1 = plot(series = 4000, color = na)
e2 = plot(series = 3000, color = na)
fill(plot1=e1, plot2=e2, color = time > 1618957756000 ? (time <= 1619908156000 + (time[0]-time[1]) ? color.red : na) : na)

if barstate.islast
    line.new(x1=1619432956000, y1=4000, x2=1619432956000, y2=3000, xloc=xloc.bar_time, color = color.red, style = line.style_arrow_right)
if barstate.islast
    line.new(x1=1618957756000, y1=3500, x2=1619908156000, y2=3500, xloc=xloc.bar_time, color = color.red, style = line.style_arrow_right)

