//@version=4
study('chartex2', overlay=true)
if barstate.islast
    label1 = label.new(x=1619168400000, y=2000, text='LINE IS HERE', xloc=xloc.bar_time, yloc=yloc.price, color=color.maroon, style=label.style_label_down, textcolor=color.black, size=size.normal, textalign=text.align_center, tooltip='')
if barstate.islast
    line.new(x1=1619168400000, y1=2000, x2=1619268400000, y2=2500, xloc=xloc.bar_time, extend=extend.both, color=color.lime, style=line.style_solid, width=1)
