//@version=4
study('chartex', overlay=true)
label.new(1619168400000, -1, text='', xloc=xloc.bar_time, yloc=yloc.price, color=color.blue, style=label.style_label_down, textcolor=color.black, size=size.normal, textalign=text.align_center, tooltip='')
if time == 1619168400000
    line.new(x1=1619168400000, y1=close, x2=1619168400001, y2=close, xloc=xloc.bar_time, extend=extend.right, color=color.blue, style=line.style_solid, width=1)
